name       : autossh
version    : 1.4f
release    : 1
source     :
    - http://www.harding.motd.ca/autossh/autossh-1.4f.tgz : 0172e5e1bea40c642e0ef025334be3aadd4ff3b4d62c0b177ed88a8384e2f8f2
license    : BSD-3-Clause
component  : network.clients
summary    : Automatically restart SSH sessions and tunnels
description: |
    autossh is a program to start a copy of ssh and monitor it,
    restarting it as necessary should it die or stop passing traffic.
builddeps  :
    - openssh
rundeps    :
    - openssh
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
